// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piqujmgdejyttuoylzsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpcXVqbWdkZWp5dHR1b3lsenN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzMxNjUsImV4cCI6MjA2NzIwOTE2NX0.TYIaQh3BTwjAYRAC9LQCr-bMdsq3foYQIaXES7F5dsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});